### ISSUE TITLE
Question about mqtt carldebilly/zigbee2mqttassistant

### ISSUE THREAD

**Issue by hppyworld** [simplynetwork/video-materials#1]
Hello, 

Thanks for nice tutorial for zigbee setup. 
I have a question is it ok not to use carldebilly/zigbee2mqttassistant? because as i understood this is just a WebUI, but if we use Home Assistant then we really do not need carldebilly/zigbee2mqttassistant.

Please explain if you think that we definitely need zigbee2mqttassistant for manage zigbee network. 

Thanks for help.

**Comment by bryhtnet** [comment]
Hi,

Zigbee2Mqtt Assistant is optional Web interface and can be removed.

In normal condition Zigbee2MQTT configuration file should have `permit_join` set to `false` and Zigbee2Mqtt Assistant Web interface in Status tab with `"ALLOW NEW DEVICE TO JOIN NETWORK"` button allows temporarily override this attribute to be able to add new sensors to the network. Also it can be useful for troubleshooting purposes to see which sensors are currently available.

However Zigbee2MQTT has a built-in Web interface which allows the same things and to enable it add the following to your configuration.yaml:
```
frontend:
  port: 8080
```
And update docker-compose.yml: 
```
services:
  zigbee2mqtt:
    ports:
      - 8080:8080

```

**Comment by hppyworld** [comment]
Thank you for nice explanation. 

I have another question regarding using host network for home assistant, as i need to connect home assistant to other wifi devices in a network. But with your setup home assistant needs to connect to zigbee network but this prevents it to use host network setting in docker-compose. 

How do you use home assistant without running in a host network to connect all your wifi devices? For example apple home kit, and TP link kasa wifi devices. Thanks for reply.

**Comment by bryhtnet** [comment]
Don't have WiFi sensors to check on, but depends on your goal. 

Home Assistant with addons (Zigbee2MQTT and Mosquitto broker) can be installed on PC directly, then you would have access to all devices.

All apps can be installed in one container, but containers are meant to separate each service to own independent environment. Each container can have multiple network interfaces and mapped devices. If containers is your way, then try to map additional resources to Home Assistant.

**Comment by hppyworld** [comment]
@simplynetwork I have tried to make Zigbee2MQTT built-in Web interface work.
I followed exact steps you mentioned above. but webbrowser get no reply when using that port. Did you try it with latest version of Zigbee2MQTT? is it really work?

Thanks.

**Comment by hppyworld** [comment]
> Don't have WiFi sensors to check on, but depends on your goal.
> 
> Home Assistant with addons (Zigbee2MQTT and Mosquitto broker) can be installed on PC directly, then you would have access to all devices.
> 
> All apps can be installed in one container, but containers are meant to separate each service to own independent environment. Each container can have multiple network interfaces and mapped devices. If containers is your way, then try to map additional resources to Home Assistant.

I also dont like WiFi sensors but its very complicated to find good quality in less price or same price as WiFi Sensors. can you please give me your list of zigbee sensors which are reliable and less price. i am looking for alternative of TPLink Kasa plug which can also have energy consumption monitoring.

**Comment by bryhtnet** [comment]
> I have tried to make Zigbee2MQTT built-in Web interface work.

This combination works as expected, also the WEB interface with previously provided config. Ensure that zigbee2mqtt is connected to mosquitto broker, seems as requirement for Web to be operational.
```
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.21.2
  mosquitto:
    image: eclipse-mosquitto:2.0.12
```


> can you please give me your list of zigbee sensors which are reliable and less price.

Can't recommend much since currently using only some Xiaomi Aqara sensors.

**Comment by hppyworld** [comment]
Thanks
